### ISSUE TITLE
Sprite sheets not working in older Firefox

### ISSUE THREAD

**Issue by ttencate** [alakajam-team/alakajam#312]
From https://alakajam.com/4th-kajam/281/prison-breakpoint/, captured in Firefox 29:

![2018-06-21-113556_766x155_scrot](https://user-images.githubusercontent.com/90930/41710987-48d9c468-7547-11e8-88d8-5bf7f0c2eaff.png)

The "PAL" is from the top left of the sprite sheet. It looks like these bits of CSS aren't being applied:

```css
.entry-results__category-medal.medal-ranking-1 {
    background-position-y: -409px;
}
.entry-results__category-medal.medal-category-1 {
    background-position: -64px -176px;
        background-position-y: -176px;
}
```

It seems like `background-position-x` and `background-position-y` are [relatively recent](https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-x) additions to the spec, and aren't fully standardised yet.

Fix: simply use `background-position` in full. With SCSS, this shouldn't lead to more repetition.
